name = "my-calendar"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "my-calendar-db"
database_id = "D1_PLACEHOLDER"  # <--- 这里改成占位符，放心提交到 GitHub

# 变量部分留空，由 Action 注入
